export type RuntimePassthroughSchemaCategory =
  | "public_contract_should_be_strict"
  | "compatibility_boundary_allowed"
  | "debug_operator_payload_allowed"
  | "legacy_storage_allowed";

export type RuntimePassthroughSchemaDisposition = "must_be_strict" | "passthrough_allowed";

export type RuntimePassthroughSchemaDeclaration = {
  schema_name: string;
  disposition: RuntimePassthroughSchemaDisposition;
  category: RuntimePassthroughSchemaCategory;
  passthrough_count: number;
  reason: string;
};

export const RUNTIME_PASSTHROUGH_SCHEMA_REGISTRY = [
  {
    schema_name: "ExecutionSummaryV1Schema",
    disposition: "must_be_strict",
    category: "public_contract_should_be_strict",
    passthrough_count: 0,
    reason: "execution_summary_v1 is a stable public runtime contract and must reject undeclared top-level fields",
  },
  {
    schema_name: "TrajectoryCompileStepSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "trajectory inputs may carry raw tool/provider payloads that the compiler normalizes downstream",
  },
  {
    schema_name: "PlannerPacketEntrySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "planner packet entries carry heterogeneous recall lines until each section has a dedicated contract",
  },
  {
    schema_name: "TrajectoryCompileContractSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "compiled trajectory contracts still preserve forward-compatible recovery details for older consumers",
  },
  {
    schema_name: "TrajectoryCompilePromotionSeedSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "promotion seeds preserve forward-compatible workflow identity hints during compiler rollout",
  },
  {
    schema_name: "TrajectoryCompileResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 2,
    reason: "trajectory compile responses retain compatibility extension fields while compile subcontracts harden",
  },
  {
    schema_name: "ContinuityFocusItemSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "continuity focus items are operator-facing diagnostics assembled from mixed memory carriers",
  },
  {
    schema_name: "ContinuityInspectSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "continuity inspection is an operator review surface and may include extra diagnostic counters",
  },
  {
    schema_name: "ContinuityReviewContractSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "review contracts carry reviewer-specific requirements while canonical execution contracts harden separately",
  },
  {
    schema_name: "ContinuityReviewPackSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "review-pack summaries are operator payloads with forward-compatible diagnostics",
  },
  {
    schema_name: "ContinuityReviewPackResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 2,
    reason: "continuity review-pack responses include operator payload extensions and nested diagnostics",
  },
  {
    schema_name: "ExperienceIntelligencePathRecommendationSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "experience recommendations remain compatibility-open while retrieval evidence contracts stabilize",
  },
  {
    schema_name: "ExperienceIntelligenceToolRecommendationSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "tool recommendations carry forward-compatible scoring metadata during recommendation hardening",
  },
  {
    schema_name: "ActionRetrievalEvidenceEntrySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "retrieval evidence entries may include source-specific metadata from heterogeneous memory records",
  },
  {
    schema_name: "ActionRetrievalEvidenceSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "retrieval evidence keeps compatibility metadata until every evidence source has a strict subtype",
  },
  {
    schema_name: "ActionRetrievalUncertaintySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "uncertainty diagnostics may grow during retrieval-gate calibration",
  },
  {
    schema_name: "ActionRetrievalGateRehydrationHintSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "rehydration hints preserve source-specific recall metadata for older integrations",
  },
  {
    schema_name: "ActionRetrievalGateSummarySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "retrieval gate summaries retain compatibility diagnostics while action contracts harden",
  },
  {
    schema_name: "ActionRetrievalResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 2,
    reason: "action retrieval responses are still a compatibility boundary for host integrations",
  },
  {
    schema_name: "PolicyHintEntrySchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "policy hints are persisted compatibility memory and may contain legacy metadata",
  },
  {
    schema_name: "DerivedPolicySurfaceSchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "derived policy surfaces bridge legacy persisted policy memory into canonical trust gates",
  },
  {
    schema_name: "PolicyContractSchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "policy contracts remain storage-compatible while authoritative policy gates own trust",
  },
  {
    schema_name: "PolicyReviewAttentionSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "policy review attention is operator-facing and may include review diagnostics",
  },
  {
    schema_name: "PolicyReviewSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "policy review summaries are operator diagnostics, not authority-producing contracts",
  },
  {
    schema_name: "PolicyGovernanceContractSchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "governance contracts preserve legacy policy payload extensions across stored memory versions",
  },
  {
    schema_name: "PolicyGovernanceApplyPayloadSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "apply payloads accept forward-compatible governance inputs from older clients",
  },
  {
    schema_name: "PersistedPolicyMemorySchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "persisted policy memory must tolerate legacy slots while resolvers produce canonical surfaces",
  },
  {
    schema_name: "PolicyGovernanceApplyResultSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "apply results keep compatibility metadata for existing governance consumers",
  },
  {
    schema_name: "DelegationLearningSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation learning summaries expose operator diagnostics during learning-loop inspection",
  },
  {
    schema_name: "DelegationLearningProjectionSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation learning projections preserve forward-compatible learning-loop diagnostics",
  },
  {
    schema_name: "ExperienceIntelligenceResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 3,
    reason: "experience intelligence is a broad compatibility route while action retrieval contracts narrow first",
  },
  {
    schema_name: "KickoffRecommendationResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 2,
    reason: "kickoff recommendation remains host-compatibility-open during startup contract hardening",
  },
  {
    schema_name: "AuthorityVisibilitySummarySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "authority visibility keeps compatibility counters while trust-gate authority remains separately enforced",
  },
  {
    schema_name: "EvolutionInspectSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "evolution inspection is an operator diagnostic surface",
  },
  {
    schema_name: "EvolutionInspectResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "evolution inspection responses may include extra diagnostics for operators",
  },
  {
    schema_name: "EvolutionReviewContractSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "evolution review contracts carry reviewer-specific diagnostic fields",
  },
  {
    schema_name: "EvolutionReviewPackSummarySchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "evolution review-pack summaries are operator diagnostics",
  },
  {
    schema_name: "EvolutionReviewPackResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "evolution review-pack responses preserve operator-facing diagnostics",
  },
  {
    schema_name: "AgentMemoryInspectResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "agent memory inspection is an operator/debug surface",
  },
  {
    schema_name: "AgentMemoryReviewPackResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "agent memory review packs are operator handoff payloads",
  },
  {
    schema_name: "AgentMemoryResumePackResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "agent memory resume packs are operator handoff payloads",
  },
  {
    schema_name: "AgentMemoryHandoffPackResponseSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "agent memory handoff packs are operator handoff payloads",
  },
  {
    schema_name: "PolicyGovernanceApplyResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "policy governance apply responses keep compatibility metadata while gate results harden",
  },
  {
    schema_name: "PlanningSummaryContractSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "planning summaries are a compatibility route surface outside the strict execution_summary_v1 contract",
  },
  {
    schema_name: "AssemblySummaryContractSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "assembly summaries are a compatibility route surface outside the strict execution_summary_v1 contract",
  },
  {
    schema_name: "ContextOperatorProjectionSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 2,
    reason: "operator projections intentionally expose diagnostic payloads to hosts",
  },
  {
    schema_name: "PlannerPacketRouteContractBaseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "planner/context routes remain host-compatibility-open while stable subcontracts narrow",
  },
  {
    schema_name: "PatternMatchAnchorContractSchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "pattern match anchors preserve legacy anchor metadata across recall and selection",
  },
  {
    schema_name: "ToolsSelectionSummaryContractSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "tools selection summaries preserve compatibility metadata while selection authority is gated elsewhere",
  },
  {
    schema_name: "ToolsSelectRouteContractSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 6,
    reason: "tools_select is a broad compatibility route with several heterogeneous nested surfaces",
  },
  {
    schema_name: "ReplayLearningProjectionResultContractSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "replay learning projection results expose learning-loop diagnostics",
  },
  {
    schema_name: "ReplayRepairReviewGovernancePolicyEffectSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "governance policy-effect previews are operator diagnostics",
  },
  {
    schema_name: "ReplayRepairReviewGovernanceDecisionTraceSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "decision traces intentionally allow diagnostic stage metadata",
  },
  {
    schema_name: "ReplayRepairReviewGovernancePreviewSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "governance previews are operator diagnostics rather than authoritative contracts",
  },
  {
    schema_name: "ReplayRepairReviewGovernanceInputSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "governance input accepts compatibility fields from existing review clients",
  },
  {
    schema_name: "ReplayPlaybookRepairReviewResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "replay repair review responses retain compatibility metadata while learning artifacts harden",
  },
  {
    schema_name: "ToolsFeedbackPatternAnchorSchema",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 1,
    reason: "tools feedback pattern anchors preserve legacy anchor metadata during pattern materialization",
  },
  {
    schema_name: "WorkflowWriteProjectionGovernanceDecisionTraceSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "workflow projection decision traces intentionally carry diagnostic metadata",
  },
  {
    schema_name: "WorkflowWriteProjectionGovernancePolicyEffectSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "workflow projection policy effects are governance diagnostics",
  },
  {
    schema_name: "WorkflowWriteProjectionGovernancePreviewSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 2,
    reason: "workflow projection previews expose operator diagnostics and nested review payloads",
  },
  {
    schema_name: "ToolsFeedbackFormPatternGovernanceDecisionTraceSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "tools feedback decision traces intentionally carry diagnostic metadata",
  },
  {
    schema_name: "ToolsFeedbackFormPatternGovernancePolicyEffectSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "tools feedback policy effects are governance diagnostics",
  },
  {
    schema_name: "ToolsFeedbackGovernancePreviewSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 2,
    reason: "tools feedback governance previews expose operator diagnostics and nested review payloads",
  },
  {
    schema_name: "ToolsFeedbackGovernanceInputSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "tools feedback governance input accepts compatibility fields from existing review clients",
  },
  {
    schema_name: "ToolsFeedbackResponseSchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "tools feedback responses keep compatibility metadata while materialized pattern contracts harden",
  },
  {
    schema_name: "DelegationRecordFindEntrySchema",
    disposition: "passthrough_allowed",
    category: "compatibility_boundary_allowed",
    passthrough_count: 1,
    reason: "delegation record find entries expose stored record metadata from mixed historical versions",
  },
  {
    schema_name: "DelegationRecordsAggregateBucketSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation aggregate buckets are analytical/operator summaries",
  },
  {
    schema_name: "DelegationRecordsAggregateRefStatSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation aggregate ref stats are analytical/operator summaries",
  },
  {
    schema_name: "DelegationRecordsAggregateStringStatSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation aggregate string stats are analytical/operator summaries",
  },
  {
    schema_name: "DelegationRecordsReusablePatternSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "reusable delegation patterns are analytical recommendations, not strict execution records",
  },
  {
    schema_name: "DelegationRecordsLearningRecommendationSchema",
    disposition: "passthrough_allowed",
    category: "debug_operator_payload_allowed",
    passthrough_count: 1,
    reason: "delegation learning recommendations are operator-facing analytics",
  },
  {
    schema_name: "MemoryPackImportRequest",
    disposition: "passthrough_allowed",
    category: "legacy_storage_allowed",
    passthrough_count: 5,
    reason: "memory pack import accepts legacy exported payload shapes for migration compatibility",
  },
] as const satisfies readonly RuntimePassthroughSchemaDeclaration[];
